services:
  server:
    build: .
    container_name: pettools
    ports:
      - 80:8081
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://pettools-db.cx0oi0guucqn.us-east-1.rds.amazonaws.com/obicho
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: FQcLHIjKDLQH3VnArUqA
    command: mvn spring-boot:run
    networks:
      - pettools
networks:
  pettools:
    driver: bridge