services:
  server:
    build: .
    container_name: pettools
    ports:
      - 80:8081
    environment:
      DB_USER: postgres
      DB_PWD: postgres
      DB_HOST: database
      DB_PORT: 5432
    command: mvn spring-boot:run
    networks:
      - pettools-network
networks:
  pettools-network:
    driver: bridge